"""
Django settings_main for main project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings_main and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings_main - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'a4-kdyji*masrj#n7)w^+0)u24&s1xag^@@a#^9bue@@ietb2v'

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = ['*']

INSTALLED_LIBRARIES = [
    'setup',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'widget_tweaks',
    # 'webpack_loader',
]

INSTALLED_MODULES = [
    'apps.templates',
    'apps.util',
    'apps.util.generic_filters',
    'apps.util.dropdown_list',
    'apps.index',
    'apps.localizations',
    'apps.solicitud',
    'apps.certificacion',
    'apps.reporte_excel',
    'apps.generic',
    'apps.reporte_grafico',
    'apps.tupa',
]

INSTALLED_APPS = INSTALLED_LIBRARIES + INSTALLED_MODULES

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'apps.middlewares.request.AppRequestMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "apps.middlewares.validar_calendario_middleware.ValidarCalendarioMiddleware",  # add custom middleware
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
]

# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, '..', 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'builtins': [
                'apps.util.generic_filters.templatetags.paginator',
                'apps.util.generic_filters.templatetags.updateurl',
                'apps.util.generic_filters.templatetags.utils', ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],

        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        },
    },
    #
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/


REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],

    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],

    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

LANGUAGE_CODE = 'es-PE'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# INIT CONFIG EMAIL --->


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_POST = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_DIRIS')
EMAIL_HOST_PASSWORD = os.environ.get('DIRIS_PASS')

# END CONFIG EMAIL --->


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'media/')

STATIC_LOCAL_ROOT = os.path.join(BASE_DIR, '..', 'static/')
# STATICFILES_DIRS = (os.path.join(BASE_DIR, '..', 'static'),)


STATICFILES_DIRS = (
    os.path.join(BASE_DIR, '..', 'static'),
    os.path.join(BASE_DIR, '..', "ui/dist"),  # Bundle de VUE
)

STATIC_URL = '/staticfiles/'
STATIC_ROOT = os.path.join(BASE_DIR, '..', 'staticfiles/')

AUTH_USER_MODEL = 'setup.usuario'

DOCS_ROOT = os.path.join(BASE_DIR, '..', 'docs/_build/html')
DOCS_ACCESS = 'public'

# SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# SESSION_COOKIE_AGE = 60  # set just 10 seconds to test
# SESSION_SAVE_EVERY_REQUEST = True

BASE_DIR_MAIN = Path(__file__).resolve().parent.parent.parent

# Directorio de Vue
UI_DIR = os.path.join(BASE_DIR_MAIN, 'ui/')

WEBPACK_LOADER = {
    'DEFAULT': {
        'CACHE': False,
        # 'BUNDLE_DIR_NAME': 'webpack_bundles/',
        'STATS_FILE': os.path.join(UI_DIR, 'webpack-stats.json'),
        'POLL_INTERVAL': 0.1,
        'IGNORE': [r'.+\.hot-update.js', r'.+\.map'],
        # 'LOADER_CLASS': 'webpack_loader.loader.WebpackLoader',
    }
}
